field: 65ea9303-bbd2-422a-ae19-a886de8e8f50 # Form
fieldLayouts:
  67bb6bca-4c26-4091-8333-1eb259aa859e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 663daeb7-a1d1-4361-a762-b785dcffdb2d # ID for label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e71bb9be-2821-4806-ae99-7fd7cdab4678
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e2ca303d-fa2f-409a-a087-c0300797fd85 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f73069e6-e22f-4b17-b662-56d1a8c72e02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 079c9584-ab1b-423d-bc1f-9d10417a9b63 # Placeholder
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5698782-9adb-42c5-a27b-4c02fe75779a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80c773df-2cd5-4252-a44d-01eabdcc5ca2
        userCondition: null
fields:
  079c9584-ab1b-423d-bc1f-9d10417a9b63: # Placeholder
    columnSuffix: reobtain
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: null
    name: Placeholder
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  663daeb7-a1d1-4361-a762-b785dcffdb2d: # ID for label
    columnSuffix: ozmrqflj
    contentColumnType: text
    fieldGroup: null
    handle: id_for_label
    instructions: null
    name: 'ID for label'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e2ca303d-fa2f-409a-a087-c0300797fd85: # Label
    columnSuffix: rieuqsaz
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: emailField
name: 'Email Field'
sortOrder: 2
