fieldLayouts:
  dae9098f-f94c-4bfc-a97a-ecd8fad81295:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f5a12b74-4c24-4b79-adae-71ec26b0b32c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d868ec23-fd63-4555-84da-9b2f617477c7
        userCondition: null
handle: uploadAddNavigation
hasTitleField: false
name: 'Upload add navigation'
section: db5dbdf1-3ffa-4332-9147-e55f62279272 # Upload add navigation
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
