fieldLayouts:
  3ca44d97-25b5-4b3e-9279-bb405b7d7b37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4dc4bb17-e380-4e65-a7c8-3a201afcf1f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e35cf0d-d9e5-4581-8e2b-97e4dd9738cc
        userCondition: null
handle: upload
hasTitleField: false
name: Upload
section: b1a02b8d-afc1-497a-9d65-4aa04a261771 # Upload
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
