fieldLayouts:
  2129752b-ef92-4364-b0de-ebe0d7e18cb6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6b66edaa-316c-4f1a-97fe-f56c51bda00b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39cc0964-7908-4496-9300-f0e053ab1db8
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
