columnSuffix: null
contentColumnType: string
fieldGroup: 2c8d0883-eb20-49d4-97e0-f2951a3aa9cb # Categories
handle: contentType
instructions: null
name: 'Content Type'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:b2d16f76-a8d7-4947-9033-a6208d319529' # Content Type
  sources: '*'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
