fieldLayouts:
  163a41f4-d8ee-417f-9ca8-c972f8a73638:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 50ad4dca-03ff-4766-8587-82cedb2c8737 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab92d1d7-1b72-40e8-9298-04f7cf6bdf8d
            userCondition: null
            warning: null
            width: 100
        name: Menu
        uid: 00d3e1ec-b289-4031-a109-2ee9ac93d5cc
        userCondition: null
handle: headerStudent
name: 'Header Student'
sortOrder: 6
