fieldLayouts:
  0675b36c-aedc-4758-a014-0003f8b5f487:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 50ad4dca-03ff-4766-8587-82cedb2c8737 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6432680-1d9d-48bd-923d-9111bfdc73f3
            userCondition: null
            warning: null
            width: 100
        name: Menu
        uid: 48c59a83-87a1-473e-b533-bb19b0650ab9
        userCondition: null
handle: headerReader
name: 'Header Reader'
sortOrder: 4
