defaultPlacement: end
enableVersioning: true
handle: myArticles
name: 'My Articles'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  de9adf7f-6fe6-4483-b882-eed90f12fddf: # HADI
    enabledByDefault: true
    hasUrls: true
    template: _pages\my-articles.twig
    uriFormat: my-articles
type: single
