defaultPlacement: end
enableVersioning: true
handle: resetPassword
name: 'Reset Password'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  de9adf7f-6fe6-4483-b882-eed90f12fddf: # HADI
    enabledByDefault: true
    hasUrls: true
    template: _pages/reset-password
    uriFormat: reset-password
type: single
