defaultPlacement: end
enableVersioning: true
handle: uploadAddNavigation
name: 'Upload add navigation'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  de9adf7f-6fe6-4483-b882-eed90f12fddf: # HADI
    enabledByDefault: true
    hasUrls: true
    template: upload/add-navigation
    uriFormat: upload-add-navigation
type: single
